name: hotel_app
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0-209.1.beta

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  dio: ^5.8.0+1
  get_it: ^8.0.3
  equatable: ^2.0.7
  go_router: ^15.1.2
  intl: ^0.20.2
  toastification: ^3.0.2
  flutter_dotenv: ^5.2.1
  freezed_annotation: ^2.4.4
  shared_preferences: ^2.5.3
  cached_network_image: ^3.4.1
  logger: ^2.5.0
  retrofit: ^4.4.2
  json_annotation: ^4.9.0
  flutter_screenutil: ^5.9.3
  introduction_screen: ^3.1.17
  flutter_native_splash: ^2.4.4
  flutter_svg: ^2.1.0
  pin_code_fields: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  json_serializable: ^6.9.5
  build_runner: ^2.4.15
  retrofit_generator: ^9.2.0
  freezed: ^2.4.1
flutter:
  uses-material-design: true

  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg
